-- MySQL Script generated by MySQL Workbench
-- Mon 03 Aug 2020 13:51:46 BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema edifyer_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema edifyer_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edifyer_db` DEFAULT CHARACTER SET utf8 ;
USE `edifyer_db` ;

-- -----------------------------------------------------
-- Table `edifyer_db`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edifyer_db`.`company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `category` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQUE_NAME` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11417
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edifyer_db`.`source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edifyer_db`.`source` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `scrape_script` VARCHAR(32) NULL DEFAULT NULL,
  `home_link` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SOURCE_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edifyer_db`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edifyer_db`.`rating` (
  `rating_id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NOT NULL,
  `source_id` INT(11) NOT NULL,
  `sd_rate` FLOAT NOT NULL,
  `uncertainty` FLOAT NOT NULL,
  `date` DATE NOT NULL,
  `source_link` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`rating_id`),
  INDEX `FK_COMPANY_idx` (`company_id` ASC),
  INDEX `FK_SOURCE` (`source_id` ASC),
  CONSTRAINT `FK_COMPANY`
    FOREIGN KEY (`company_id`)
    REFERENCES `edifyer_db`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SOURCE`
    FOREIGN KEY (`source_id`)
    REFERENCES `edifyer_db`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11419
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
